# Created using wingetcreate 1.0.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: LocktimeSoftware.NetLimiter4
PackageVersion: 4.1.13.0
InstallerSwitches:
  Silent: /exenoui /quiet
  SilentWithProgress: /exenoui /passive
Installers:
- Architecture: neutral
  InstallerType: exe
  InstallerUrl: https://netlimiter.com/files/download/nl4/netlimiter-4.1.13.0.exe
  InstallerSha256: 0F73A63DBDC9D7CDF367E85BC8F0B67ECBAD79F9D112FEDD57F142AEEFEC4C86
ManifestType: installer
ManifestVersion: 1.1.0

